# Our hello world action
name: hello-world

on:
  push:
    branch: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Say Hi
      - name: Print hello world
        run: echo Hello everyone

      - name: Print Machine name
        run: hostname
